// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvDGQbaOkeClJTA6yjuIuNpKvuVlUQoY',
    appId: '1:532857129599:web:32b10f82f350f943a4cd4a',
    messagingSenderId: '532857129599',
    projectId: 'flutter-phone-auth-c1bb1',
    authDomain: 'flutter-phone-auth-c1bb1.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-c1bb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZPdu536OnUiq8ClAZpOWk702UyrOGOs',
    appId: '1:532857129599:android:8971e392ac489286a4cd4a',
    messagingSenderId: '532857129599',
    projectId: 'flutter-phone-auth-c1bb1',
    storageBucket: 'flutter-phone-auth-c1bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw55U6R96BlXTBeimlbaWS94AMsAudxdE',
    appId: '1:532857129599:ios:ba14dc2f751c13aaa4cd4a',
    messagingSenderId: '532857129599',
    projectId: 'flutter-phone-auth-c1bb1',
    storageBucket: 'flutter-phone-auth-c1bb1.appspot.com',
    iosClientId: '532857129599-o7a2plkuu6mseha95m5fp9qodqskgou5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePhoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw55U6R96BlXTBeimlbaWS94AMsAudxdE',
    appId: '1:532857129599:ios:ba14dc2f751c13aaa4cd4a',
    messagingSenderId: '532857129599',
    projectId: 'flutter-phone-auth-c1bb1',
    storageBucket: 'flutter-phone-auth-c1bb1.appspot.com',
    iosClientId: '532857129599-o7a2plkuu6mseha95m5fp9qodqskgou5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebasePhoneAuth',
  );
}
